import js from '@eslint/js';
import tseslint from '@typescript-eslint/eslint-plugin';
import tsparser from '@typescript-eslint/parser';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';

export default [
  {
    ignores: [
      'dist/**',
      '.next/**',
      '**/.next/**',
      'nextjs_space/.next/**',
      'nextjs_space/**/.next/**',
      'test-results/**',
      '**/test-results/**',
      'playwright-report/**',
      '**/playwright-report/**',
      'nextjs_space/next.config.js',
      'nextjs_space/scripts/**',
      'apps/**',
      'node_modules/**',
      'build/**',
      'coverage/**',
      '*.min.js',
      '*.bundle.js',
      '**/*.bundle.js',
      '**/*.min.js',
      '**/vendor-*.js',
      '**/admin-vendor-*.js',
      '**/base44-vendor-*.js',
      '**/react-vendor-*.js',
      '**/ai-vendor-*.js',
      '**/http-vendor-*.js',
      '**/ui-vendor-*.js',
      '**/modules-vendor-*.js',
      '**/utils-vendor-*.js',
      '**/monaco-vendor-*.js',
      '**/supabase-vendor-*.js',
      'api-server*.cjs',
      'api-tester.js',
      'jest.setup.cjs',
      '*.config.cjs',
      '*.setup.cjs',
      'middleware/**',
      'production-server.cjs',
      'public/service-worker.js',
      'public/sw.js',
      'scripts/**/*.cjs',
      'scripts/**/*.js',
      'server/scripts/**',
      'public/**',
      'nextjs_space/next.config.js',
      'nextjs_space/public/sw.js',
      'types/speech.d.ts',
      'types/serviceworker.d.ts',
      'setup-supabase-db.js',
      'test-auth.cjs',
      'test-login-api.js',
    ],
  },
  js.configs.recommended,
  {
    files: ['**/*.js'],
    languageOptions: {
      sourceType: 'module',
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
      },
    },
  },
  {
    files: ['**/*.cjs'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
      },
    },
  },
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        global: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        FormData: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        Headers: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': tseslint,
      react,
      'react-hooks': reactHooks,
    },
    rules: {
      'no-case-declarations': 'off',
      'no-unreachable': 'off',
      'no-redeclare': 'off',
      'react/react-in-jsx-scope': 'off',
      'no-unused-vars': 'off',
      'no-undef': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
    },
    settings: {
      react: {
        version: 'detect',
      },
    },
  },
];
