-- ═══════════════════════════════════════════════════════════════════════════
-- CortexBuild Pro - Production Seed Data
-- Real Construction Management Data for Enterprise SaaS
-- ═══════════════════════════════════════════════════════════════════════════
-- Target: 100+ organizations, 200+ users, 50+ projects, 1000+ documents
--           500+ tasks, 100+ companies, API integration data
-- ═══════════════════════════════════════════════════════════════════════════

-- ═══════════════════════════════════════════════════════════════════════════
-- 1. ORGANIZATIONS (100 companies - GCs, Subs, Owners, Architects)
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO "Organization" (id, name, slug, logoUrl, industry, size, description, plan, entitlements, storageUsedBytes, isActive, createdAt, updatedAt) VALUES
-- Enterprise General Contractors
('org-gc-001', 'Turner Construction Company', 'turner-construction', 'https://logo.clearbit.com/turnerconstruction.com', 'Construction', '5000-10000', 'Leading general contractor specializing in commercial buildings', 'ENTERPRISE', '{"modules":{"projects":true,"tasks":true,"documents":true,"rfis":true,"submittals":true,"changeOrders":true,"dailyReports":true,"safety":true,"reports":true,"team":true,"budget":true,"schedule":true,"quality":true},"limits":{"storageGB":500,"maxUsers":500,"maxProjects":1000}}', 0, true, NOW(), NOW()),
('org-gc-002', 'Bechtel Corporation', 'bechtel-corp', 'https://logo.clearbit.com/bechtel.com', 'Heavy Civil', '10000+', 'Infrastructure and energy construction leader', 'ENTERPRISE', '{"modules":{"projects":true,"tasks":true,"documents":true,"rfis":true,"submittals":true,"changeOrders":true,"dailyReports":true,"safety":true,"reports":true,"team":true,"budget":true,"schedule":true,"quality":true},"limits":{"storageGB":500,"maxUsers":500,"maxProjects":1000}}', 0, true, NOW(), NOW()),
('org-gc-003', 'Skanska USA', 'skanska-usa', 'https://logo.clearbit.com/skanska.com', 'Construction', '5000-10000', 'Commercial construction and development', 'ENTERPRISE', '{"modules":{"projects":true,"tasks":true,"documents":true,"rfis":true,"submittals":true,"changeOrders":true,"dailyReports":true,"safety":true,"reports":true,"team":true,"budget":true,"schedule":true,"quality":true},"limits":{"storageGB":500,"maxUsers":500,"maxProjects":1000}}', 0, true, NOW(), NOW()),
('org-gc-004', 'Kiewit Corporation', 'kiewit-corp', 'https://logo.clearbit.com/kiewit.com', 'Heavy Civil', '10000+', 'Engineering and construction organization', 'ENTERPRISE', '{"modules":{"projects":true,"tasks":true,"documents":true,"rfis":true,"submittals":true,"changeOrders":true,"dailyReports":true,"safety":true,"reports":true,"team":true,"budget":true,"schedule":true,"quality":true},"limits":{"storageGB":500,"maxUsers":500,"maxProjects":1000}}', 0, true, NOW(), NOW()),
('org-gc-005', 'DPR Construction', 'dpr-construction', 'https://logo.clearbit.com/dpr.com', 'Commercial', '1000-5000', 'Technical builder for complex projects', 'ENTERPRISE', '{"modules":{"projects":true,"tasks":true,"documents":true,"rfis":true,"submittals":true,"changeOrders":true,"dailyReports":true,"safety":true,"reports":true,"team":true,"budget":true,"schedule":true,"quality":true},"limits":{"storageGB":500,"maxUsers":500,"maxProjects":1000}}', 0, true, NOW(), NOW()),
-- Regional General Contractors
('org-gc-006', 'Suffolk Construction', 'suffolk-construction', 'https://logo.clearbit.com/suffolk.com', 'Construction', '1000-5000', 'Building the future since 1975', 'PROFESSIONAL', '{"modules":{"projects":true,"tasks":true,"documents":true,"rfis":true,"submittals":true,"changeOrders":true,"dailyReports":true,"safety":true,"reports":true,"team":true,"budget":true,"schedule":true},"limits":{"storageGB":100,"maxUsers":100,"maxProjects":200}}', 0, true, NOW(), NOW()),
('org-gc-007', 'Bovee Company', 'bovee-company', 'https://logo.clearbit.com/bovee.com', 'Commercial', '500-1000', 'General contractor for healthcare', 'PROFESSIONAL', '{"modules":{"projects":true,"tasks":true,"documents":true,"rfis":true,"submittals":true,"changeOrders":true,"dailyReports":true,"safety":true,"reports":true,"team":true,"budget":true},"limits":{"storageGB":100,"maxUsers":100,"maxProjects":200}}', 0, true, NOW(), NOW()),
('org-gc-008', 'McCarthy Building Companies', 'mccarthy-buildings', 'https://logo.clearbit.com/mccarthy.com', 'Construction', '1000-5000', 'National commercial builder', 'ENTERPRISE', '{"modules":{"projects":true,"tasks":true,"documents":true,"rfis":true,"submittals":true,"changeOrders":true,"dailyReports":true,"safety":true,"reports":true,"team":true,"budget":true,"schedule":true,"quality":true},"limits":{"storageGB":500,"maxUsers":500,"maxProjects":1000}}', 0, true, NOW(), NOW()),
-- Specialty Subcontractors
('org-sub-001', 'M.C. Electric Company', 'mc-electric', 'https://logo.clearbit.com/mcelectric.com', 'Electrical', '100-500', 'Electrical contractor for commercial projects', 'PROFESSIONAL', '{"modules":{"projects":true,"tasks":true,"documents":true,"rfis":true,"submittals":true,"dailyReports":true,"safety":true,"team":true,"budget":true},"limits":{"storageGB":50,"maxUsers":50,"maxProjects":50}}', 0, true, NOW(), NOW()),
('org-sub-002', 'ABC Plumbing Inc', 'abc-plumbing', NULL, 'Plumbing', '50-100', 'Commercial plumbing services', 'STARTER', '{"modules":{"projects":true,"tasks":true,"documents":true,"rfis":true,"submittals":true,"dailyReports":true,"safety":true,"team":true},"limits":{"storageGB":20,"maxUsers":20,"maxProjects":20}}', 0, true, NOW(), NOW()),
('org-sub-003', 'Steel Erectors LLC', 'steel-erectors', NULL, 'Steel', '100-500', 'Structural steel installation', 'PROFESSIONAL', '{"modules":{"projects":true,"tasks":true,"documents":true,"rfis":true,"submittals":true,"dailyReports":true,"safety":true,"team":true,"budget":true},"limits":{"storageGB":50,"maxUsers":50,"maxProjects":50}}', 0, true, NOW(), NOW()),
('org-sub-004', 'Concrete Solutions', 'concrete-solutions', NULL, 'Concrete', '50-100', 'Concrete foundations and flatwork', 'STARTER', '{"modules":{"projects":true,"tasks":true,"documents":true,"rfis":true,"dailyReports":true,"safety":true,"team":true},"limits":{"storageGB":20,"maxUsers":20,"maxProjects":20}}', 0, true, NOW(), NOW()),
('org-sub-005', 'HVAC Masters', 'hvac-masters', NULL, 'HVAC', '100-500', 'Mechanical and HVAC systems', 'PROFESSIONAL', '{"modules":{"projects":true,"tasks":true,"documents":true,"rfis":true,"submittals":true,"dailyReports":true,"safety":true,"team":true,"budget":true},"limits":{"storageGB":50,"maxUsers":50,"maxProjects":50}}', 0, true, NOW(), NOW()),
-- Architecture & Engineering
('org-ae-001', 'Gensler', 'gensler', 'https://logo.clearbit.com/gensler.com', 'Architecture', '5000-10000', 'Global architecture firm', 'ENTERPRISE', '{"modules":{"projects":true,"tasks":true,"documents":true,"rfis":true,"submittals":true,"changeOrders":true,"dailyReports":true,"safety":true,"reports":true,"team":true,"budget":true,"schedule":true,"quality":true,"drawings":true},"limits":{"storageGB":500,"maxUsers":500,"maxProjects":1000}}', 0, true, NOW(), NOW()),
('org-ae-002', 'HKS Architects', 'hks-architects', 'https://logo.clearbit.com/hksinc.com', 'Architecture', '1000-5000', 'Healthcare and sports architecture', 'ENTERPRISE', '{"modules":{"projects":true,"tasks":true,"documents":true,"rfis":true,"submittals":true,"changeOrders":true,"dailyReports":true,"safety":true,"reports":true,"team":true,"budget":true,"schedule":true,"quality":true,"drawings":true},"limits":{"storageGB":500,"maxUsers":500,"maxProjects":1000}}', 0, true, NOW(), NOW()),
('org-ae-003', 'Arup Engineering', 'arup-eng', 'https://logo.clearbit.com/arup.com', 'Engineering', '1000-5000', 'Structural and MEP engineering', 'ENTERPRISE', '{"modules":{"projects":true,"tasks":true,"documents":true,"rfis":true,"submittals":true,"changeOrders":true,"dailyReports":true,"safety":true,"reports":true,"team":true,"budget":true,"schedule":true,"quality":true},"limits":{"storageGB":500,"maxUsers":500,"maxProjects":1000}}', 0, true, NOW(), NOW()),
('org-ae-004', 'Thornton Tomasetti', 'thornton-tomasetti', 'https://logo.clearbit.com/thorntontomasetti.com', 'Structural', '500-1000', 'Structural engineering specialists', 'PROFESSIONAL', '{"modules":{"projects":true,"tasks":true,"documents":true,"rfis":true,"submittals":true,"changeOrders":true,"dailyReports":true,"safety":true,"reports":true,"team":true,"budget":true,"drawings":true},"limits":{"storageGB":100,"maxUsers":100,"maxProjects":200}}', 0, true, NOW(), NOW()),
-- Project Owners / Developers
('org-owner-001', 'Related Companies', 'related-companies', 'https://logo.clearbit.com/related.com', 'Real Estate', '1000-5000', 'Luxury real estate developer', 'ENTERPRISE', '{"modules":{"projects":true,"tasks":true,"documents":true,"rfis":true,"submittals":true,"changeOrders":true,"dailyReports":true,"safety":true,"reports":true,"team":true,"budget":true,"schedule":true,"quality":true},"limits":{"storageGB":500,"maxUsers":500,"maxProjects":1000}}', 0, true, NOW(), NOW()),
('org-owner-002', 'Hines', 'hines', 'https://logo.clearbit.com/hines.com', 'Real Estate', '1000-5000', 'Global real estate firm', 'ENTERPRISE', '{"modules":{"projects":true,"tasks":true,"documents":true,"rfis":true,"submittals":true,"changeOrders":true,"dailyReports":true,"safety":true,"reports":true,"team":true,"budget":true,"schedule":true,"quality":true},"limits":{"storageGB":500,"maxUsers":500,"maxProjects":1000}}', 0, true, NOW(), NOW()),
('org-owner-003', 'Tishman Speyer', 'tishman-speyer', 'https://logo.clearbit.com/tishmanspeyer.com', 'Real Estate', '500-1000', 'Commercial property developer', 'PROFESSIONAL', '{"modules":{"projects":true,"tasks":true,"documents":true,"rfis":true,"submittals":true,"changeOrders":true,"dailyReports":true,"safety":true,"reports":true,"team":true,"budget":true,"schedule":true},"limits":{"storageGB":100,"maxUsers":100,"maxProjects":200}}', 0, true, NOW(), NOW()),
('org-owner-004', 'Boston Properties', 'boston-properties', 'https://logo.clearbit.com/bostonproperties.com', 'Real Estate', '500-1000', 'Office REIT developer', 'PROFESSIONAL', '{"modules":{"projects":true,"tasks":true,"documents":true,"rfis":true,"submittals":true,"changeOrders":true,"dailyReports":true,"safety":true,"reports":true,"team":true,"budget":true,"schedule":true},"limits":{"storageGB":100,"maxUsers":100,"maxProjects":200}}', 0, true, NOW(), NOW()),
-- Small contractors
('org-small-001', 'Smith Builders LLC', 'smith-builders', NULL, 'Residential', '10-50', 'Custom home builder', 'STARTER', '{"modules":{"projects":true,"tasks":true,"documents":true,"rfis":true,"dailyReports":true,"safety":true,"team":true},"limits":{"storageGB":10,"maxUsers":10,"maxProjects":10}}', 0, true, NOW(), NOW()),
('org-small-002', 'Johnson Remodeling', 'johnson-remodeling', NULL, 'Remodeling', '5-10', 'Kitchen and bath remodeling', 'FREE', '{"modules":{"projects":true,"tasks":true,"documents":true,"rfis":true,"team":true},"limits":{"storageGB":5,"maxUsers":5,"maxProjects":5}}', 0, true, NOW(), NOW()),
('org-small-003', 'Quick Fix Construction', 'quick-fix-construction', NULL, 'Repair', '10-50', 'Emergency repairs and maintenance', 'STARTER', '{"modules":{"projects":true,"tasks":true,"documents":true,"rfis":true,"dailyReports":true,"safety":true,"team":true},"limits":{"storageGB":10,"maxUsers":10,"maxProjects":10}}', 0, true, NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- Generate remaining 75 organizations programmatically via Python script
-- (See seed_script.py for bulk generation)

-- ═══════════════════════════════════════════════════════════════════════════
-- 2. USERS (200+ users across all organizations)
-- ═══════════════════════════════════════════════════════════════════════════

-- Enterprise GC - Turner Construction (50 users)
INSERT INTO "User" (id, email, password, name, role, avatarUrl, phone, organizationId, emailVerified, createdAt, updatedAt) VALUES
('user-gc001-001', 'james.mitchell@turnerconstruction.com', '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYqKx8pB4W', 'James Mitchell', 'COMPANY_OWNER', 'https://i.pravatar.cc/150?u=user-gc001-001', '+1-617-555-0101', 'org-gc-001', NOW(), NOW(), NOW()),
('user-gc001-002', 'sarah.chen@turnerconstruction.com', '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYqKx8pB4W', 'Sarah Chen', 'ADMIN', 'https://i.pravatar.cc/150?u=user-gc001-002', '+1-617-555-0102', 'org-gc-001', NOW(), NOW(), NOW()),
('user-gc001-003', 'michael.o''brien@turnerconstruction.com', '$2a$12$LQv3c1yqBWVHxkd0LHAk