#!/bin/bash

echo "🚀 Setting up Supabase database for CortexBuild..."
echo ""

# Supabase project details
PROJECT_ID="qglvhxkgbzujglehewsa"
SUPABASE_URL="https://qglvhxkgbzujglehewsa.supabase.co"

echo "📊 Project: supabase-green-grass"
echo "🌐 URL: $SUPABASE_URL"
echo ""

echo "📝 MANUAL SETUP REQUIRED:"
echo ""
echo "1. Go to Supabase SQL Editor:"
echo "   https://supabase.com/dashboard/project/$PROJECT_ID/sql/new"
echo ""
echo "2. Copy the entire content from:"
echo "   supabase/COMPLETE_SCHEMA.sql"
echo ""
echo "3. Paste it into the SQL Editor"
echo ""
echo "4. Click 'Run' button"
echo ""
echo "5. Verify tables created in Table Editor:"
echo "   - companies (3 rows)"
echo "   - users (3 rows)"
echo "   - projects"
echo "   - sdk_apps (6 rows)"
echo "   - user_app_installations"
echo "   - company_app_installations"
echo "   - app_review_history"
echo "   - app_analytics"
echo "   - activities"
echo ""
echo "6. Update password hashes by running this SQL:"
echo ""
echo "   UPDATE users SET password_hash = crypt('parola123', gen_salt('bf', 10)) WHERE email = 'adrian.stanca1@gmail.com';"
echo "   UPDATE users SET password_hash = crypt('lolozania1', gen_salt('bf', 10)) WHERE email = 'adrian@ascladdingltd.co.uk';"
echo "   UPDATE users SET password_hash = crypt('password123', gen_salt('bf', 10)) WHERE email = 'adrian.stanca1@icloud.com';"
echo ""
echo "✅ After setup, test with:"
echo "   🔴 Super Admin: adrian.stanca1@gmail.com / parola123"
echo "   🟠 Company Admin: adrian@ascladdingltd.co.uk / lolozania1"
echo "   🟢 Developer: adrian.stanca1@icloud.com / password123"
echo ""
echo "🎉 Ready to deploy!"

