#!/bin/bash
# =============================================================================
# CortexBuild Pro - Deployment Scripts Helper
# =============================================================================
# Shows available deployment and maintenance scripts with descriptions
# =============================================================================

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${CYAN}"
echo "============================================================================="
echo "  CortexBuild Pro - Deployment Scripts"
echo "  Version: $(cat ../VERSION 2>/dev/null || echo 'unknown')"
echo "============================================================================="
echo -e "${NC}"
echo ""

echo -e "${GREEN}📦 Deployment Scripts:${NC}"
echo ""
echo -e "  ${BLUE}./production-deploy.sh${NC}"
echo "    Complete production workflow: commit, rebuild, deploy, cleanup"
echo "    ⭐ Recommended for production updates"
echo ""
echo -e "  ${BLUE}./one-click-deploy.sh${NC}"
echo "    Fresh VPS setup with all prerequisites"
echo "    Best for initial installation"
echo ""
echo -e "  ${BLUE}./deploy.sh${NC}"
echo "    Basic deployment without extras"
echo "    Quick deploy without cleanup"
echo ""
echo -e "  ${BLUE}./cloudpanel-deploy.sh${NC}"
echo "    CloudPanel-specific deployment"
echo "    For CloudPanel hosting environments"
echo ""

echo -e "${GREEN}🧹 Maintenance Scripts:${NC}"
echo ""
echo -e "  ${BLUE}./cleanup-repos.sh${NC}"
echo "    Standard repository cleanup"
echo "    Removes unused Docker artifacts, cleans git, logs"
echo ""
echo -e "  ${BLUE}./cleanup-repos.sh --aggressive${NC}"
echo "    Aggressive cleanup (use with caution)"
echo "    Removes all unused Docker images and volumes"
echo ""
echo -e "  ${BLUE}./health-check.sh${NC}"
echo "    Comprehensive deployment health check"
echo "    Verifies containers, database, app, resources"
echo ""

echo -e "${GREEN}💾 Backup & Restore:${NC}"
echo ""
echo -e "  ${BLUE}./backup.sh${NC}"
echo "    Create database backup"
echo "    Stored in /root/cortexbuild_backups/"
echo ""
echo -e "  ${BLUE}./restore.sh [backup_file]${NC}"
echo "    Restore database from backup"
echo "    Example: ./restore.sh backups/db_20240123.sql.gz"
echo ""
echo -e "  ${BLUE}./rollback.sh${NC}"
echo "    Interactive rollback to previous backup"
echo "    Includes safety backup before rollback"
echo ""

echo -e "${GREEN}🔐 Security & Setup:${NC}"
echo ""
echo -e "  ${BLUE}./setup-ssl.sh [domain] [email]${NC}"
echo "    Setup SSL certificates with Let's Encrypt"
echo "    Example: ./setup-ssl.sh example.com admin@example.com"
echo ""
echo -e "  ${BLUE}./seed-db.sh${NC}"
echo "    Seed database with initial data"
echo "    Run once after first deployment"
echo ""

echo -e "${GREEN}📊 Monitoring:${NC}"
echo ""
echo "  ${BLUE}docker compose ps${NC}              - Container status"
echo "  ${BLUE}docker compose logs -f app${NC}     - View application logs"
echo "  ${BLUE}docker stats${NC}                   - Resource usage"
echo "  ${BLUE}./health-check.sh${NC}             - Full health check"
echo ""

echo -e "${GREEN}🔄 Quick Commands:${NC}"
echo ""
echo "  ${BLUE}# Production update${NC}"
echo "  git pull && ./production-deploy.sh"
echo ""
echo "  ${BLUE}# Health check after deploy${NC}"
echo "  ./health-check.sh"
echo ""
echo "  ${BLUE}# Clean up disk space${NC}"
echo "  ./cleanup-repos.sh --aggressive"
echo ""
echo "  ${BLUE}# Backup before major changes${NC}"
echo "  ./backup.sh"
echo ""

echo -e "${GREEN}📚 Documentation:${NC}"
echo ""
echo "  README.md                  - Complete deployment guide"
echo "  QUICKSTART.md              - Quick start guide"
echo "  PRODUCTION-DEPLOY-GUIDE.md - Production deployment guide ⭐"
echo "  CLOUDPANEL-GUIDE.md        - CloudPanel specific guide"
echo ""

echo -e "${YELLOW}💡 Tip:${NC} For production updates, use: ${BLUE}./production-deploy.sh${NC}"
echo -e "${YELLOW}💡 Tip:${NC} Read ${BLUE}PRODUCTION-DEPLOY-GUIDE.md${NC} for detailed instructions"
echo ""
