import React, { useState, useEffect, useCallback, useRef } from 'react';
import {
    Bot, Briefcase, Calculator, Shield, Send, Plus, Clock, AlertTriangle,
    CheckCircle2, XCircle, RefreshCw, ChevronRight, FileText, Users, Zap,
    TrendingUp, PoundSterling, Award, Bell, Clipboard, BarChart3, Wallet,
    ArrowRight, Calendar, Download, Info, HardHat, Wrench, Flame
} from 'lucide-react';
import { useToast } from '@/contexts/ToastContext';
import { apiClient } from '@/services/apiClient';

type ViewTab = 'AGENTS' | 'COMPLIANCE' | 'PAYSLIPS' | 'CASHFLOW' | 'GRANTS';
type AgentType = 'bizadvisor' | 'accountsbot' | 'opsbot';

interface AgentMessage { id: string; role: 'user' | 'assistant'; content: string; actions?: any[]; createdAt: string; }
interface ComplianceTask { id: string; title: string; category: string; priority: string; status: string; dueDate: string; regulatoryRef?: string; assigneeName?: string; autoGenerated?: boolean; notes?: string; }
interface Payslip { id: string; employeeName: string; periodStart: string; periodEnd: string; payDate: string; grossPay: number; netPay: number; paye: number; employeeNI: number; cisDeduction: number; pensionEmployee: number; hoursWorked: number; yearToDateGross: number; yearToDateNet: number; status: string; }

const AGENT_CONFIGS: Record<AgentType, { name: string; icon: any; color: string; description: string; starters: string[] }> = {
    bizadvisor: { name: 'BizAdvisorBot', icon: Briefcase, color: 'bg-indigo-500', description: 'Strategic business insights, growth opportunities & risk assessment', starters: ['How is my business doing?', 'What are my key risks?', 'Show profit by project', 'How can I grow?'] },
    accountsbot: { name: 'AccountsBot', icon: Calculator, color: 'bg-emerald-500', description: 'VAT, CIS, retentions, cash flow predictions & HMRC compliance', starters: ['Calculate my VAT', 'Explain CIS deductions', "What's my cash position?", 'Help with payroll'] },
    opsbot: { name: 'OpsBot', icon: Shield, color: 'bg-amber-500', description: 'Project risks, compliance tracking, certifications & scheduling', starters: ["What's overdue?", 'Show task summary', "What's expiring?", 'Safety score'] },
};

const AIAgentsView: React.FC = () => {
    const { addToast } = useToast();
    const [activeTab, setActiveTab] = useState<ViewTab>('AGENTS');
    const [isLoading, setIsLoading] = useState(false);

    // Agent state
    const [activeAgent, setActiveAgent] = useState<AgentType | null>(null);
    const [sessionId, setSessionId] = useState<string | null>(null);
    const [messages, setMessages] = useState<AgentMessage[]>([]);
    const [inputMessage, setInputMessage] = useState('');
    const [isSending, setIsSending] = useState(false);
    const chatEndRef = useRef<HTMLDivElement>(null);

    // Compliance state
    const [complianceTasks, setComplianceTasks] = useState<ComplianceTask[]>([]);
    // Payslip state
    const [payslips, setPayslips] = useState<Payslip[]>([]);
    // Cash flow state
    const [cashFlowData, setCashFlowData] = useState<any>(null);
    // Grants state
    const [grantsData, setGrantsData] = useState<any>(null);

    const fmt = (n: number) => new Intl.NumberFormat('en-GB', { style: 'currency', currency: 'GBP' }).format(n);

    // ─── Agent Chat ─────────────────────────────────────────────────────────
    const startAgentSession = async (agentType: AgentType) => {
        setActiveAgent(agentType);
        setMessages([]);
        try {
            const result = await apiClient.post('/ai-agents/sessions', { agentType });
            setSessionId((result as any)?.id);
        } catch { addToast('Failed to start agent session', 'error'); }
    };

    const sendMessage = async () => {
        if (!inputMessage.trim() || !sessionId || isSending) return;
        const userMsg = inputMessage.trim();
        setInputMessage('');
        setMessages(prev => [...prev, { id: Date.now().toString(), role: 'user', content: userMsg, createdAt: new Date().toISOString() }]);
        setIsSending(true);

        try {
            const result: any = await apiClient.post(`/ai-agents/sessions/${sessionId}/message`, { message: userMsg });
            if (result?.assistantMessage) {
                setMessages(prev => [...prev, result.assistantMessage]);
            }
        } catch { addToast('Agent failed to respond', 'error'); }
        setIsSending(false);
    };

    useEffect(() => { chatEndRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages]);

    // ─── Tab Data Loading ───────────────────────────────────────────────────
    const loadTabData = useCallback(async (tab: ViewTab) => {
        setIsLoading(true);
        try {
            switch (tab) {
                case 'COMPLIANCE':
                    const tasks = await apiClient.get('/ai-agents/compliance/tasks');
                    if (Array.isArray(tasks)) setComplianceTasks(tasks);
                    break;
                case 'PAYSLIPS':
                    const slips = await apiClient.get('/ai-agents/payslips');
                    if (Array.isArray(slips)) setPayslips(slips);
                    break;
                case 'CASHFLOW':
                    const cf = await apiClient.post('/ai-agents/cash-flow/predict', { months: 3 });
                    if (cf) setCashFlowData(cf);
                    break;
                case 'GRANTS':
                    const grants = await apiClient.get('/ai-agents/grants/eligibility');
                    if (grants) setGrantsData(grants);
                    break;
            }
        } catch (err) { console.warn('Failed to load tab data:', err); }
        setIsLoading(false);
    }, []);

    useEffect(() => { if (activeTab !== 'AGENTS') loadTabData(activeTab); }, [activeTab, loadTabData]);

    const handleGenerateComplianceTasks = async () => {
        try {
            const result: any = await apiClient.post('/ai-agents/compliance/generate-tasks', {});
            addToast(`Generated ${result?.generated || 0} compliance tasks`, 'success');
            loadTabData('COMPLIANCE');
        } catch { addToast('Failed to generate tasks', 'error'); }
    };

    const handleCompleteTask = async (taskId: string) => {
        try {
            await apiClient.put(`/ai-agents/compliance/tasks/${taskId}/complete`, {});
            addToast('Task completed', 'success');
            loadTabData('COMPLIANCE');
        } catch { addToast('Failed to complete task', 'error'); }
    };

    const tabs = [
        { id: 'AGENTS' as ViewTab, label: 'AI Agents', icon: Bot },
        { id: 'COMPLIANCE' as ViewTab, label: 'Compliance Tasks', icon: Clipboard },
        { id: 'PAYSLIPS' as ViewTab, label: 'Payslips', icon: FileText },
        { id: 'CASHFLOW' as ViewTab, label: 'Cash Flow', icon: TrendingUp },
        { id: 'GRANTS' as ViewTab, label: 'Grant Finder', icon: Award },
    ];

    return (
        <div className="p-8 max-w-[1600px] mx-auto h-full flex flex-col overflow-y-auto">
            <div className="mb-8">
                <h1 className="text-3xl font-black text-zinc-900 tracking-tight">AI Command Centre</h1>
                <p className="text-zinc-500 mt-1">Intelligent agents, compliance automation & financial insights</p>
            </div>

            {/* Tab Nav */}
            <div className="flex gap-1 border-b border-zinc-200 mb-6 overflow-x-auto pb-px">
                {tabs.map(tab => (
                    <button key={tab.id} onClick={() => setActiveTab(tab.id)} className={`flex items-center gap-2 px-4 py-3 text-sm font-medium whitespace-nowrap border-b-2 transition-colors ${activeTab === tab.id ? 'border-zinc-900 text-zinc-900' : 'border-transparent text-zinc-500 hover:text-zinc-700'}`}>
                        <tab.icon size={16} />{tab.label}
                    </button>
                ))}
            </div>

            {isLoading && <div className="flex items-center justify-center py-20"><RefreshCw size={24} className="animate-spin text-zinc-400" /><span className="ml-3 text-zinc-500">Loading...</span></div>}

            {/* AGENTS TAB */}
            {!isLoading && activeTab === 'AGENTS' && !activeAgent && (
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    {(Object.entries(AGENT_CONFIGS) as [AgentType, typeof AGENT_CONFIGS[AgentType]][]).map(([type, cfg]) => (
                        <div key={type} className="bg-white rounded-2xl border border-zinc-200 p-6 hover:shadow-xl transition-shadow cursor-pointer" onClick={() => startAgentSession(type)}>
                            <div className={`w-14 h-14 ${cfg.color} rounded-2xl flex items-center justify-center mb-4`}><cfg.icon size={28} className="text-white" /></div>
                            <h3 className="text-xl font-black text-zinc-900 mb-2">{cfg.name}</h3>
                            <p className="text-sm text-zinc-500 mb-4">{cfg.description}</p>
                            <div className="space-y-2">
                                {cfg.starters.map((s, i) => (
                                    <div key={i} className="text-xs bg-zinc-50 text-zinc-600 px-3 py-2 rounded-lg flex items-center gap-2"><ChevronRight size={12} />{s}</div>
                                ))}
                            </div>
                            <button className="mt-4 w-full py-3 bg-zinc-900 text-white rounded-xl text-sm font-bold hover:bg-zinc-800 flex items-center justify-center gap-2"><Bot size={16} /> Start Conversation</button>
                        </div>
                    ))}
                </div>
            )}

            {/* AGENT CHAT */}
            {!isLoading && activeTab === 'AGENTS' && activeAgent && (
                <div className="flex flex-col flex-1 bg-white rounded-2xl border border-zinc-200 overflow-hidden" style={{ minHeight: '500px' }}>
                    {/* Chat Header */}
                    <div className="flex items-center gap-3 p-4 border-b border-zinc-100">
                        <div className={`w-10 h-10 ${AGENT_CONFIGS[activeAgent].color} rounded-xl flex items-center justify-center`}>
                            {React.createElement(AGENT_CONFIGS[activeAgent].icon, { size: 20, className: 'text-white' })}
                        </div>
                        <div className="flex-1"><h3 className="font-bold text-zinc-900">{AGENT_CONFIGS[activeAgent].name}</h3><p className="text-xs text-zinc-400">{AGENT_CONFIGS[activeAgent].description}</p></div>
                        <button onClick={() => { setActiveAgent(null); setSessionId(null); setMessages([]); }} className="px-3 py-1.5 text-xs font-medium bg-zinc-100 text-zinc-600 rounded-lg hover:bg-zinc-200">Close</button>
                    </div>

                    {/* Messages */}
                    <div className="flex-1 overflow-y-auto p-4 space-y-4">
                        {messages.length === 0 && (
                            <div className="text-center py-8">
                                <p className="text-zinc-400 mb-4">Ask me anything. Here are some suggestions:</p>
                                <div className="flex flex-wrap gap-2 justify-center">
                                    {AGENT_CONFIGS[activeAgent].starters.map((s, i) => (
                                        <button key={i} onClick={() => { setInputMessage(s); }} className="px-4 py-2 bg-zinc-50 text-zinc-700 rounded-full text-sm hover:bg-zinc-100">{s}</button>
                                    ))}
                                </div>
                            </div>
                        )}
                        {messages.map(msg => (
                            <div key={msg.id} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                                <div className={`max-w-[80%] p-4 rounded-2xl ${msg.role === 'user' ? 'bg-zinc-900 text-white' : 'bg-zinc-50 text-zinc-900'}`}>
                                    <div className="text-sm whitespace-pre-wrap leading-relaxed" dangerouslySetInnerHTML={{ __html: formatMarkdown(msg.content) }} />
                                </div>
                            </div>
                        ))}
                        {isSending && <div className="flex justify-start"><div className="bg-zinc-50 px-4 py-3 rounded-2xl"><div className="flex gap-1"><div className="w-2 h-2 bg-zinc-300 rounded-full animate-bounce" /><div className="w-2 h-2 bg-zinc-300 rounded-full animate-bounce" style={{ animationDelay: '0.1s' }} /><div className="w-2 h-2 bg-zinc-300 rounded-full animate-bounce" style={{ animationDelay: '0.2s' }} /></div></div></div>}
                        <div ref={chatEndRef} />
                    </div>

                    {/* Input */}
                    <div className="p-4 border-t border-zinc-100">
                        <div className="flex gap-2">
                            <input value={inputMessage} onChange={e => setInputMessage(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); sendMessage(); } }} placeholder="Ask the agent..." className="flex-1 px-4 py-3 bg-zinc-50 border border-zinc-200 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-zinc-900" />
                            <button onClick={sendMessage} disabled={isSending || !inputMessage.trim()} className="px-4 py-3 bg-zinc-900 text-white rounded-xl hover:bg-zinc-800 disabled:opacity-50"><Send size={18} /></button>
                        </div>
                    </div>
                </div>
            )}

            {/* COMPLIANCE TAB */}
            {!isLoading && activeTab === 'COMPLIANCE' && (
                <div className="space-y-6">
                    <div className="flex justify-between items-center">
                        <div>
                            <h3 className="text-lg font-bold text-zinc-900">Compliance Task Scheduler</h3>
                            <p className="text-sm text-zinc-500">Auto-generated tasks for MEWP checks, toolbox talks, certifications & safety inspections</p>
                        </div>
                        <button onClick={handleGenerateComplianceTasks} className="px-4 py-2 bg-zinc-900 text-white rounded-lg text-sm font-bold hover:bg-zinc-800 flex items-center gap-2"><Zap size={16} /> Generate Tasks</button>
                    </div>

                    {/* Summary Cards */}
                    <div className="grid grid-cols-4 gap-4">
                        <StatCard icon={<AlertTriangle size={18} />} label="Overdue" value={complianceTasks.filter(t => t.status === 'pending' && new Date(t.dueDate) < new Date()).length} color="red" />
                        <StatCard icon={<Clock size={18} />} label="Pending" value={complianceTasks.filter(t => t.status === 'pending').length} color="amber" />
                        <StatCard icon={<CheckCircle2 size={18} />} label="Completed" value={complianceTasks.filter(t => t.status === 'completed').length} color="emerald" />
                        <StatCard icon={<HardHat size={18} />} label="Auto-Generated" value={complianceTasks.filter(t => t.autoGenerated).length} color="blue" />
                    </div>

                    {/* Task List */}
                    <div className="bg-white rounded-xl border border-zinc-200 overflow-hidden">
                        {complianceTasks.length > 0 ? (
                            <div className="divide-y divide-zinc-100">
                                {complianceTasks.map(task => {
                                    const isOverdue = task.status === 'pending' && new Date(task.dueDate) < new Date();
                                    const priorityColors: Record<string, string> = { Critical: 'bg-red-100 text-red-700', High: 'bg-amber-100 text-amber-700', Medium: 'bg-blue-100 text-blue-700', Low: 'bg-zinc-100 text-zinc-600' };
                                    const catIcons: Record<string, any> = { 'Health & Safety': HardHat, 'Fire Safety': Flame, 'Working at Height': ArrowRight, 'Electrical Safety': Zap, 'Plant & Equipment': Wrench, 'Certifications': Award };
                                    const CatIcon = catIcons[task.category] || Clipboard;
                                    return (
                                        <div key={task.id} className={`flex items-center justify-between p-4 ${isOverdue ? 'bg-red-50' : 'hover:bg-zinc-50'}`}>
                                            <div className="flex items-center gap-3">
                                                <div className={`w-8 h-8 rounded-lg flex items-center justify-center ${isOverdue ? 'bg-red-100' : 'bg-zinc-100'}`}><CatIcon size={16} className={isOverdue ? 'text-red-600' : 'text-zinc-500'} /></div>
                                                <div>
                                                    <p className="text-sm font-medium text-zinc-900">{task.title}</p>
                                                    <p className="text-xs text-zinc-400">{task.category} {task.regulatoryRef && `| ${task.regulatoryRef}`} | Due: {new Date(task.dueDate).toLocaleDateString('en-GB')}</p>
                                                </div>
                                            </div>
                                            <div className="flex items-center gap-2">
                                                <span className={`px-2 py-1 text-[10px] font-bold rounded-full ${priorityColors[task.priority] || priorityColors.Medium}`}>{task.priority}</span>
                                                {task.status === 'pending' && (
                                                    <button onClick={() => handleCompleteTask(task.id)} className="px-3 py-1.5 text-xs font-medium bg-emerald-100 text-emerald-700 rounded-lg hover:bg-emerald-200 flex items-center gap-1"><CheckCircle2 size={14} /> Complete</button>
                                                )}
                                                {task.status === 'completed' && <span className="px-2 py-1 text-[10px] font-bold bg-emerald-100 text-emerald-700 rounded-full">DONE</span>}
                                            </div>
                                        </div>
                                    );
                                })}
                            </div>
                        ) : (
                            <Empty icon={<Clipboard size={40} />} title="No Compliance Tasks" desc="Click 'Generate Tasks' to create MEWP checks, toolbox talks, and safety inspections." />
                        )}
                    </div>
                </div>
            )}

            {/* PAYSLIPS TAB */}
            {!isLoading && activeTab === 'PAYSLIPS' && (
                <div className="space-y-6">
                    <div><h3 className="text-lg font-bold text-zinc-900">Employee Payslips</h3><p className="text-sm text-zinc-500">View issued payslips with PAYE, NI, CIS deductions and year-to-date totals</p></div>
                    <div className="bg-white rounded-xl border border-zinc-200 overflow-hidden">
                        {payslips.length > 0 ? (
                            <div className="overflow-x-auto">
                                <table className="w-full text-sm">
                                    <thead><tr className="bg-zinc-50 text-zinc-500 text-xs uppercase">
                                        <th className="text-left p-3 font-semibold">Employee</th>
                                        <th className="text-left p-3 font-semibold">Period</th>
                                        <th className="text-right p-3 font-semibold">Gross</th>
                                        <th className="text-right p-3 font-semibold">PAYE</th>
                                        <th className="text-right p-3 font-semibold">NI</th>
                                        <th className="text-right p-3 font-semibold">CIS</th>
                                        <th className="text-right p-3 font-semibold">Pension</th>
                                        <th className="text-right p-3 font-semibold">Net Pay</th>
                                        <th className="text-right p-3 font-semibold">YTD Gross</th>
                                        <th className="text-right p-3 font-semibold">Hours</th>
                                    </tr></thead>
                                    <tbody className="divide-y divide-zinc-100">
                                        {payslips.map(slip => (
                                            <tr key={slip.id} className="hover:bg-zinc-50">
                                                <td className="p-3 font-medium text-zinc-900">{slip.employeeName}</td>
                                                <td className="p-3 text-zinc-500 text-xs">{new Date(slip.periodStart).toLocaleDateString('en-GB')} - {new Date(slip.periodEnd).toLocaleDateString('en-GB')}</td>
                                                <td className="p-3 text-right text-zinc-900 font-medium">{fmt(slip.grossPay)}</td>
                                                <td className="p-3 text-right text-red-600">{fmt(slip.paye)}</td>
                                                <td className="p-3 text-right text-red-600">{fmt(slip.employeeNI)}</td>
                                                <td className="p-3 text-right text-amber-600">{fmt(slip.cisDeduction)}</td>
                                                <td className="p-3 text-right text-zinc-500">{fmt(slip.pensionEmployee)}</td>
                                                <td className="p-3 text-right text-emerald-600 font-bold">{fmt(slip.netPay)}</td>
                                                <td className="p-3 text-right text-zinc-400">{fmt(slip.yearToDateGross)}</td>
                                                <td className="p-3 text-right text-zinc-500">{slip.hoursWorked}</td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        ) : (
                            <Empty icon={<FileText size={40} />} title="No Payslips" desc="Generate payslips from the Payroll tab in Accounting Hub after processing a payroll run." />
                        )}
                    </div>
                </div>
            )}

            {/* CASH FLOW TAB */}
            {!isLoading && activeTab === 'CASHFLOW' && (
                <div className="space-y-6">
                    <div><h3 className="text-lg font-bold text-zinc-900">Predictive Cash Flow Analysis</h3><p className="text-sm text-zinc-500">AI-powered 3-month cash flow forecast based on historical trends</p></div>

                    {cashFlowData ? (
                        <>
                            {/* Forecast Cards */}
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                {(cashFlowData.forecast || []).map((f: any, i: number) => (
                                    <div key={i} className="bg-white p-5 rounded-xl border border-zinc-200">
                                        <p className="text-xs font-semibold text-zinc-500 uppercase">{f.month}</p>
                                        <p className={`text-2xl font-black mt-1 ${f.projectedNet >= 0 ? 'text-emerald-600' : 'text-red-600'}`}>{fmt(f.projectedNet)}</p>
                                        <div className="flex justify-between text-xs text-zinc-400 mt-2">
                                            <span>In: {fmt(f.projectedIncome)}</span>
                                            <span>Out: {fmt(f.projectedExpenses)}</span>
                                        </div>
                                        <div className="mt-2 flex items-center gap-2">
                                            <div className="flex-1 h-1.5 bg-zinc-100 rounded-full"><div className="h-full bg-blue-500 rounded-full" style={{ width: `${f.confidence}%` }} /></div>
                                            <span className="text-[10px] text-zinc-400">{f.confidence}% conf</span>
                                        </div>
                                    </div>
                                ))}
                            </div>

                            {/* Insights */}
                            <div className="bg-white rounded-xl border border-zinc-200 p-6">
                                <h4 className="font-bold text-zinc-900 mb-3 flex items-center gap-2"><Zap size={18} className="text-amber-500" /> AI Insights</h4>
                                <div className="space-y-2">
                                    {(cashFlowData.insights || []).map((insight: string, i: number) => (
                                        <div key={i} className="flex items-start gap-2 text-sm text-zinc-700"><ArrowRight size={14} className="text-zinc-400 mt-0.5 shrink-0" />{insight}</div>
                                    ))}
                                </div>
                                <div className="mt-4 pt-4 border-t border-zinc-100 flex gap-6 text-sm">
                                    <span className="text-zinc-500">Upcoming Receivables: <strong className="text-zinc-900">{fmt(cashFlowData.upcomingReceivables || 0)}</strong></span>
                                    <span className="text-zinc-500">Monthly Payroll Est: <strong className="text-zinc-900">{fmt(cashFlowData.monthlyPayrollEstimate || 0)}</strong></span>
                                </div>
                            </div>

                            {/* Historical */}
                            <div className="bg-white rounded-xl border border-zinc-200 p-6">
                                <h4 className="font-bold text-zinc-900 mb-3">Historical (Last 6 Months)</h4>
                                <div className="space-y-2">
                                    {(cashFlowData.historical || []).map((h: any, i: number) => (
                                        <div key={i} className="flex items-center justify-between text-sm">
                                            <span className="text-zinc-500 w-20">{h.month}</span>
                                            <span className="text-emerald-600">{fmt(h.income)}</span>
                                            <span className="text-red-600">{fmt(h.expenses)}</span>
                                            <span className={`font-bold ${h.net >= 0 ? 'text-emerald-600' : 'text-red-600'}`}>{fmt(h.net)}</span>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </>
                    ) : (
                        <Empty icon={<TrendingUp size={40} />} title="No Forecast Data" desc="Cash flow predictions will appear after transactions are recorded." />
                    )}
                </div>
            )}

            {/* GRANTS TAB */}
            {!isLoading && activeTab === 'GRANTS' && (
                <div className="space-y-6">
                    <div><h3 className="text-lg font-bold text-zinc-900">Grant Eligibility Finder</h3><p className="text-sm text-zinc-500">UK construction grants, tax credits, and funding opportunities</p></div>

                    {grantsData ? (
                        <>
                            <div className="grid grid-cols-3 gap-4">
                                <div className="bg-emerald-50 p-5 rounded-xl border border-emerald-200">
                                    <p className="text-xs font-semibold text-emerald-600 uppercase">Eligible Grants</p>
                                    <p className="text-3xl font-black text-emerald-700 mt-1">{grantsData.eligibleGrants}</p>
                                </div>
                                <div className="bg-blue-50 p-5 rounded-xl border border-blue-200">
                                    <p className="text-xs font-semibold text-blue-600 uppercase">Potential Funding</p>
                                    <p className="text-3xl font-black text-blue-700 mt-1">{fmt(grantsData.totalPotentialFunding || 0)}</p>
                                </div>
                                <div className="bg-zinc-50 p-5 rounded-xl border border-zinc-200">
                                    <p className="text-xs font-semibold text-zinc-500 uppercase">Company Profile</p>
                                    <p className="text-sm text-zinc-700 mt-2">{grantsData.companyProfile?.projectCount || 0} projects, {grantsData.companyProfile?.employeeCount || 0} employees</p>
                                </div>
                            </div>

                            <div className="space-y-4">
                                {(grantsData.grants || []).map((grant: any, i: number) => (
                                    <div key={i} className={`bg-white p-5 rounded-xl border ${grant.eligibility ? 'border-emerald-200' : 'border-zinc-200 opacity-60'}`}>
                                        <div className="flex items-start justify-between">
                                            <div>
                                                <div className="flex items-center gap-2 mb-1">
                                                    <h4 className="font-bold text-zinc-900">{grant.name}</h4>
                                                    {grant.eligibility ? <span className="px-2 py-0.5 text-[10px] font-bold bg-emerald-100 text-emerald-700 rounded-full">ELIGIBLE</span> : <span className="px-2 py-0.5 text-[10px] font-bold bg-zinc-100 text-zinc-500 rounded-full">NOT ELIGIBLE</span>}
                                                </div>
                                                <p className="text-xs text-zinc-400">{grant.provider}</p>
                                                <p className="text-sm text-zinc-600 mt-2">{grant.description}</p>
                                                <p className="text-xs text-zinc-500 mt-1">{grant.reason}</p>
                                            </div>
                                            <div className="text-right">
                                                <p className="text-lg font-black text-zinc-900">Up to {fmt(grant.maxAmount)}</p>
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </>
                    ) : (
                        <Empty icon={<Award size={40} />} title="Loading Grants" desc="Checking your eligibility for UK construction grants and funding." />
                    )}
                </div>
            )}
        </div>
    );
};

// ─── Helpers ────────────────────────────────────────────────────────────────

function formatMarkdown(text: string): string {
    return text
        .replace(/## (.*)/g, '<h3 class="text-base font-bold mb-2 mt-3">$1</h3>')
        .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
        .replace(/^- (.*)/gm, '<div class="flex gap-2 ml-2"><span class="text-zinc-400">•</span><span>$1</span></div>')
        .replace(/^\d+\. (.*)/gm, '<div class="ml-2">$&</div>')
        .replace(/\n/g, '<br/>');
}

const StatCard: React.FC<{ icon: React.ReactNode; label: string; value: number; color: string }> = ({ icon, label, value, color }) => {
    const colors: Record<string, string> = { red: 'bg-red-50 text-red-600 border-red-200', amber: 'bg-amber-50 text-amber-600 border-amber-200', emerald: 'bg-emerald-50 text-emerald-600 border-emerald-200', blue: 'bg-blue-50 text-blue-600 border-blue-200' };
    return (
        <div className={`p-4 rounded-xl border ${colors[color]}`}>
            <div className="flex items-center gap-2 mb-1 opacity-80">{icon}<span className="text-xs font-semibold uppercase">{label}</span></div>
            <p className="text-2xl font-black">{value}</p>
        </div>
    );
};

const Empty: React.FC<{ icon: React.ReactNode; title: string; desc: string }> = ({ icon, title, desc }) => (
    <div className="flex flex-col items-center justify-center py-16 text-center">
        <div className="text-zinc-300 mb-4">{icon}</div>
        <h4 className="font-bold text-zinc-700 mb-1">{title}</h4>
        <p className="text-sm text-zinc-400 max-w-sm">{desc}</p>
    </div>
);

export default AIAgentsView;
